# Generated by Django 4.1.6 on 2023-02-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mptt_graph", "0003_treenode_graph"),
    ]

    operations = [
        migrations.RemoveField(model_name="treenode", name="graph",),
    ]
